apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
      - name: shop
        image: nginx
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: shop-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-config
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;

    pid        /var/run/nginx.pid;

    load_module /usr/lib/nginx/modules/ngx_http_js_module.so;

    events {}

    http {
        default_type text/plain;

        js_import /etc/nginx/headers.js;
        js_set \$headers headers.getRequestHeaders;

        server {
            listen 8080;
            return 200 "\$headers";
        }
    }
  headers.js: |-
    function getRequestHeaders(r) {
        let s = "Headers:\n";
        for (let h in r.headersIn) {
        s += \`  header '\${h}' is '\${r.headersIn[h]}'\n\`;
        }
        return s;
    }
    export default {getRequestHeaders};
---
apiVersion: v1
kind: Service
metadata:
  name: shop
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: shop
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: shop-gateway
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    port: 80
    protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: shop-httproute
spec:
  parentRefs:
  - name: shop-gateway
    sectionName: http
  hostnames:
  - "whatigot.lab.f5npi.net"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /cart 
    filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        add:
        - name: Accept-Encoding
          value: compress
        remove:
        - X-Apply-Discounts
    backendRefs:
    - name: shop
      port: 80